version: '3.7'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: 'unless-stopped'
    expose:
      - '27017'
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=graphql
