version: '3.7'

services:
  server:
    container_name: api-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - 4431
    ports:
      - 4431:4431
    restart: 'unless-stopped'

  mongo:
    container_name: mongodb
    image: mongo
    restart: 'unless-stopped'
    expose:
      - '27017'
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: graphql
